# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DDMRnext.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import serial
s = serial.Serial('COM5', 9600, timeout=2)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(576, 395)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.OdometryLine = QtWidgets.QLineEdit(self.frame_4)
        self.OdometryLine.setObjectName("OdometryLine")
        self.horizontalLayout_3.addWidget(self.OdometryLine)
        self.SendOdometry = QtWidgets.QPushButton(self.frame_4)
        self.SendOdometry.setObjectName("SendOdometry")
        self.horizontalLayout_3.addWidget(self.SendOdometry)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.PWMLine = QtWidgets.QLineEdit(self.frame_7)
        self.PWMLine.setObjectName("PWMLine")
        self.horizontalLayout_5.addWidget(self.PWMLine)
        self.SendPWM = QtWidgets.QPushButton(self.frame_7)
        self.SendPWM.setObjectName("SendPWM")
        self.horizontalLayout_5.addWidget(self.SendPWM)
        self.verticalLayout.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.frame_8)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.verticalLayout.addWidget(self.frame_8)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_6)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.frame_6)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_16 = QtWidgets.QFrame(self.centralwidget)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_12 = QtWidgets.QFrame(self.frame_16)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.textEdit = QtWidgets.QTextEdit(self.frame_12)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_10.addWidget(self.textEdit)
        self.label_4 = QtWidgets.QLabel(self.frame_12)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4)
        self.verticalLayout_4.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.frame_16)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.textEdit_2 = QtWidgets.QTextEdit(self.frame_13)
        self.textEdit_2.setObjectName("textEdit_2")
        self.horizontalLayout_11.addWidget(self.textEdit_2)
        self.label_5 = QtWidgets.QLabel(self.frame_13)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_11.addWidget(self.label_5)
        self.verticalLayout_4.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.frame_16)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.textEdit_3 = QtWidgets.QTextEdit(self.frame_14)
        self.textEdit_3.setObjectName("textEdit_3")
        self.horizontalLayout_12.addWidget(self.textEdit_3)
        self.label_6 = QtWidgets.QLabel(self.frame_14)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_12.addWidget(self.label_6)
        self.verticalLayout_4.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.frame_16)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.textEdit_4 = QtWidgets.QTextEdit(self.frame_15)
        self.textEdit_4.setObjectName("textEdit_4")
        self.horizontalLayout_13.addWidget(self.textEdit_4)
        self.label_7 = QtWidgets.QLabel(self.frame_15)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_13.addWidget(self.label_7)
        self.verticalLayout_4.addWidget(self.frame_15)
        self.horizontalLayout.addWidget(self.frame_16)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_11 = QtWidgets.QFrame(self.frame_2)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.LeftBtn = QtWidgets.QPushButton(self.frame_11)
        self.LeftBtn.setObjectName("LeftBtn")
        self.horizontalLayout_8.addWidget(self.LeftBtn)
        self.horizontalLayout_7.addWidget(self.frame_11)
        self.frame_9 = QtWidgets.QFrame(self.frame_2)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ForwardBtn = QtWidgets.QPushButton(self.frame_9)
        self.ForwardBtn.setObjectName("ForwardBtn")
        self.verticalLayout_3.addWidget(self.ForwardBtn)
        self.StopBtn = QtWidgets.QPushButton(self.frame_9)
        self.StopBtn.setObjectName("StopBtn")
        self.verticalLayout_3.addWidget(self.StopBtn)
        self.BackwardBtn = QtWidgets.QPushButton(self.frame_9)
        self.BackwardBtn.setObjectName("BackwardBtn")
        self.verticalLayout_3.addWidget(self.BackwardBtn)
        self.horizontalLayout_7.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.frame_2)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.RightBtn = QtWidgets.QPushButton(self.frame_10)
        self.RightBtn.setObjectName("RightBtn")
        self.horizontalLayout_9.addWidget(self.RightBtn)
        self.horizontalLayout_7.addWidget(self.frame_10)
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 576, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.SendOdometry.clicked.connect(self.show_line)
        self.SendPWM.clicked.connect(self.show_edittext)
        self.ForwardBtn.clicked.connect(self.gerak_maju)
        self.BackwardBtn.clicked.connect(self.gerak_mundur)
        self.LeftBtn.clicked.connect(self.belok_kiri)
        self.RightBtn.clicked.connect(self.belok_kanan)
        self.StopBtn.clicked.connect(self.berhenti)
        self.pushButton.clicked.connect(self.control_mode)
        self.pushButton_2.clicked.connect(self.control_setting)
        self.pushButton_3.clicked.connect(self.otomatis_mode)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)  

    def show_line(self):
        print(self.OdometryLine.text())
        odometryValue = self.OdometryLine.text()
        print(odometryValue)

        if odometryValue:
            print(odometryValue)
            s.write(odometryValue.encode())
            print(f'Odometry Value "{odometryValue} sent to Arduino')

        else:
            print('Odometry value is empty. Please enter a value.')

    def show_edittext(self):
        print(self.PWMLine.text())
        PWMValue = self.PWMLine.text()
        print(PWMValue)

        if PWMValue:
            print(PWMValue)
            s.write(PWMValue.encode())
            print(f'PWM value "{PWMValue}" sent to Arduino')

        else:
            print('PWM value is empty. Please enter a value.')

    def gerak_maju(self):
        try:
            s.write(b'w') 
            print("maju")
        except Exception as e:
            print(f'Something went wrong: {e}')
    
    def gerak_mundur(self):
        try:
            s.write(b's')  
            print("mundur")
        except Exception as e:
            print(f'Something went wrong: {e}')

    def belok_kanan(self):
        try:
            s.write(b'd')  
            print("kanan")
        except Exception as e:
            print(f'Something went wrong: {e}')

    def belok_kiri(self):
        try:
            s.write(b'a')  
            print("kiri")
        except Exception as e:
            print(f'Something went wrong: {e}')

    def berhenti(self):
        try:
            s.write(b'q')  
            print("stop")
        except Exception as e:
            print(f'Something went wrong: {e}')

    def control_mode(self):
        try:
            s.write(b'k')  
            print("Control Mode activated")
        except Exception as e:
            print(f'Something went wrong: {e}')

    def control_setting(self):
        try:
            s.write(b'j')  
            print("Control Setting activated")
        except Exception as e:
            print(f'Something went wrong: {e}')

    def otomatis_mode(self):
        try:
            s.write(b'l')  
            print("Control otomatis activated")
        except Exception as e:
            print(f'Something went wrong: {e}')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Input nilai odometry"))
        self.SendOdometry.setText(_translate("MainWindow", "Kirim"))
        self.label_2.setText(_translate("MainWindow", "Setting nilai PWM"))
        self.SendPWM.setText(_translate("MainWindow", "Kirim"))
        self.label_3.setText(_translate("MainWindow", "Play mode"))
        self.pushButton.setText(_translate("MainWindow", "Manual mode"))
        self.pushButton_3.setText(_translate("MainWindow", "Auto mode"))
        self.pushButton_2.setText(_translate("MainWindow", "Setting mode"))
        self.label_4.setText(_translate("MainWindow", "cmL"))
        self.label_5.setText(_translate("MainWindow", "cmR"))
        self.label_6.setText(_translate("MainWindow", "ErrL"))
        self.label_7.setText(_translate("MainWindow", "ErrR"))
        self.LeftBtn.setText(_translate("MainWindow", "Kiri"))
        self.ForwardBtn.setText(_translate("MainWindow", "Maju"))
        self.StopBtn.setText(_translate("MainWindow", "Berhenti"))
        self.BackwardBtn.setText(_translate("MainWindow", "Mundur"))
        self.RightBtn.setText(_translate("MainWindow", "Kanan"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
